name: Build and release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          go build -o crtforge-Linux-x86_64 -v .
          GOOS=linux GOARCH=arm64 go build -o crtforge-Linux-arm64 -v .
          GOOS=darwin GOARCH=amd64 go build -o crtforge-Darwin-x86_64 -v . 
          GOOS=darwin GOARCH=arm64 go build -o crtforge-Darwin-arm64 -v .

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            crtforge-Linux-x86_64
            crtforge-Linux-arm64
            crtforge-Darwin-x86_64
            crtforge-Darwin-arm64
