name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Get Metadata'
        id: metadata
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch --tags --force
          previousTag=$(git tag --sort=-v:refname | grep -v '\-beta' | grep -v '\-alpha' | head -n 1 | tail -n 1)
          version=$(git describe --tags --abbrev=0)
          commitId=$(git rev-parse --short $version)
          releaseBinary=true
          if [[ "${version}" == *"beta"* || "${version}" == *"alpha"* ]]; then
            echo "Tag contains beta or alpha, skipping release."
            releaseBinary=false
          fi
          echo "previousTag=$previousTag" >> "$GITHUB_OUTPUT"
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "commitId=$commitId" >> "$GITHUB_OUTPUT"
          echo "releaseBinary=$releaseBinary" >> "$GITHUB_OUTPUT"
          echo "test"

      - name: 'Docker Metadata'
        id: dockerMetadata
        uses: docker/metadata-action@v5
        with:
          images: |
            safderun/crtforge
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Binary Build
        run: |
          mkdir build
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X crtforge/cmd.version=$version -X crtforge/cmd.commitId=$commitId" -o build/crtforge-Linux-x86_64 -v .
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X crtforge/cmd.version=$version -X crtforge/cmd.commitId=$commitId" -o build/crtforge-Linux-arm64 -v .
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X crtforge/cmd.version=$version -X crtforge/cmd.commitId=$commitId" -o build/crtforge-Darwin-x86_64 -v . 
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-X crtforge/cmd.version=$version -X crtforge/cmd.commitId=$commitId" -o build/crtforge-Darwin-arm64 -v .
        env:
          version: ${{ steps.metadata.outputs.version }}
          commitId: ${{ steps.metadata.outputs.commitId }}

      - name: '✏️ Generate release changelog'
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ steps.metadata.outputs.previousTag }}

      - name: Container Image Build and push amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          labels: ${{ steps.dockerMetadata.outputs.labels }}
          file: Dockerfile.production
          build-args: |
            binary=build/crtforge-Linux-x86_64

      - name: Container Image Build and push arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ steps.dockerMetadata.outputs.tags }}
          labels: ${{ steps.dockerMetadata.outputs.labels }}
          file: Dockerfile.production
          build-args: |
            binary=build/crtforge-Linux-arm64

      - name: Release
        if: steps.metadata.outputs.releaseBinary == 'true'
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          files: |
            build/crtforge-Linux-x86_64
            build/crtforge-Linux-arm64
            build/crtforge-Darwin-x86_64
            build/crtforge-Darwin-arm64
